# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trav-Book' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Trav-Book
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  target 'Trav-BookTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
